import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useAccount } from "wagmi";
import { Chat } from "@pushprotocol/uiweb";


export default function Home(props) {
  // const { address1 } = useAccount();
  var address1 = '0x7ED790A1Ac108b9A50e24f5c5E061df59e3673a7';

  return (


    <div className={styles.container}>
      <Head>
        <title>Create Next App</title> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Noodles! 🍜</a>
        </h1>

        <p className={styles.description}>
         Decentralised Live Stream Platform.
        </p>

        <div className={styles.grid}>
          <a href="/user/0x1da502D83c2967cD185E9179376F1edA3DC52922" className={styles.card}>
            <h2>👏 Start Streaming &rarr;</h2>
            <p>Create a Stream using Livepeer via OBS. Create an NFT for streams w/ data stored via Pinata (IPFS).</p>
          </a>

          <a href="" className={styles.card}>
            <h2>🔥 Incentivise your viewers </h2>
            <p>Give them a custom generated NFT using ENS avatar and others.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>💖 Support your fav streamers</h2>
            <p>Viewers can subscribe to content via Superfluid.  Cancel anytime! </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>⛽️ Gasless NFT Minting</h2>
            <p>
              Viewers can mint NFT without paying gas w/ NFTport on Polygon Network.
            </p>
          </a>
        </div>
      </main>
      <Chat
          account="0x7ED790A1Ac108b9A50e24f5c5E061df59e3673a7" //user address
          supportAddress="0xC76139fcB9e4952CE9Fb3183C6c3af69534233FE" //support address
          apiKey="jVPMCRom1B.iDRMswdehJG7NpHDiECIHwYMMv6k2KzkPJscFIDyW8TtSnk4blYnGa8DIkfuacU0"
          env="staging"
          modalTitle='Support team'
        />

    </div>
  )
}
